#!/bin/sh
# postinst script for gh2lp

set -e

case "$1" in
  configure)
    adduser --disabled-password  --quiet --system \
      --home /var/lib/gh2lp \
      --gecos "GitHub-to-Launchpad build daemon" --group gh2lp

    addgroup --quiet --system gh2lp || true
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

