#!/bin/sh
# postinst script for gh2lp

set -e

case "$1" in
  configure)
    adduser --disabled-password  --quiet --system \
      --home /var/lib/gh2lp \
      --gecos "GitHub-to-Launchpad build daemon" --group gh2lp

    addgroup --quiet --system gh2lp || true

    if [ -d /etc/gh2lp ]; then
      chown -R gh2lp.gh2lp /etc/gh2lp
      chmod -R 600 /etc/gh2lp
    fi

    if [ -d /var/lib/gh2lp ]; then
      chown -R gh2lp.gh2lp /var/lib/gh2lp
    fi

    if [ -f /etc/init/gh2lp.conf ]; then
      chmod 600 /etc/init/gh2lp.conf
    fi
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac


#DEBHELPER#

exit 0

